"""Componentes de aprendizado para o pipeline LiDAR → FlexSim.

As importações deste pacote são leves e não exigem PyTorch. O dataset só
carrega torch quando solicitado com ``return_tensors=True``.
"""

from .classes import (
    CLASS_NAMES,
    CLASS_TO_INDEX,
    INDEX_TO_CLASS,
    WAREHOUSE_CLASS_NAMES,
    WAREHOUSE_CLASS_TO_INDEX,
    WAREHOUSE_INDEX_TO_CLASS,
    class_index_to_name,
    class_name_to_index,
    class_to_index,
    decode_class_indices,
    encode_class_names,
    index_to_class,
    normalize_class_name,
)
from .data import (
    DEFAULT_BIN_FEATURES,
    DEFAULT_NUM_POINTS,
    PointSample,
    WarehouseBox,
    WarehouseDataset,
    WarehousePointDataset,
    WarehouseSegmentationDataset,
    WarehouseScan,
    assign_point_labels,
    carregar_bin,
    label_points,
    ler_labels,
    load_bin,
    load_labels,
    load_scan,
    load_warehouse_bin,
    prepare_point_sample,
    prepare_sample,
    read_label_file,
    rotular_pontos,
    sample_fixed_points,
    temporal_split,
)
from .geometry import (
    OrientedBox,
    box_corners,
    points_in_oriented_box,
    points_inside_oriented_box,
    pontos_na_caixa_orientada,
)
from .config import PointNet2Config, TrainingConfig, load_config, save_config
from .preprocessing import PointPreprocessingConfig, preprocess_points
from .dependencies import MissingOptionalDependency, pyg_available, torch_available
from .checkpoints import load_checkpoint, save_checkpoint
from .inference import inferir_scan, predict_points
from .models.pointnet2_seg import PointNet2Segmentation
from .training import smoke_train, train_model

__all__ = [
    "CLASS_NAMES",
    "CLASS_TO_INDEX",
    "DEFAULT_BIN_FEATURES",
    "DEFAULT_NUM_POINTS",
    "INDEX_TO_CLASS",
    "OrientedBox",
    "PointSample",
    "WarehouseBox",
    "WAREHOUSE_CLASS_NAMES",
    "WAREHOUSE_CLASS_TO_INDEX",
    "WAREHOUSE_INDEX_TO_CLASS",
    "WarehouseDataset",
    "WarehousePointDataset",
    "WarehouseSegmentationDataset",
    "WarehouseScan",
    "assign_point_labels",
    "box_corners",
    "carregar_bin",
    "class_index_to_name",
    "class_name_to_index",
    "class_to_index",
    "decode_class_indices",
    "encode_class_names",
    "index_to_class",
    "label_points",
    "ler_labels",
    "load_bin",
    "load_labels",
    "load_scan",
    "load_warehouse_bin",
    "normalize_class_name",
    "pontos_na_caixa_orientada",
    "points_in_oriented_box",
    "points_inside_oriented_box",
    "prepare_point_sample",
    "preprocess_points",
    "prepare_sample",
    "read_label_file",
    "rotular_pontos",
    "sample_fixed_points",
    "temporal_split",
    "MissingOptionalDependency",
    "PointNet2Config",
    "PointPreprocessingConfig",
    "PointNet2Segmentation",
    "TrainingConfig",
    "inferir_scan",
    "load_checkpoint",
    "load_config",
    "predict_points",
    "pyg_available",
    "save_checkpoint",
    "save_config",
    "smoke_train",
    "train_model",
    "torch_available",
]
